server:
 port: 8081

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/AuthModule
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  app:
   firebase-configuration-file: stocks-forum-firebase-adminsdk-se0gx-24bca6a5e5.json
