server:
  port: 5007
spring:
  main:
    allow-circular-references: true
  data:
    mongodb:

      uri: mongodb+srv://nilusroy0:gTKbIhWYQI2Vck80@cluster0.rihh4ek.mongodb.net/AuthModule?retryWrites=true&w=majority
#      uri:  mongodb://localhost:27017/AuthModule
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
